### ISSUE TITLE
Browser shortcuts write in hastebin

### ISSUE THREAD

**Issue by bepvte** [toptal/haste-server#143]
Pressing ctrl+tab in firefox to switch tabs puts a tab in the hatebin document. This makes everyday shortcuts cause random characters to appear in the hastebin document.

Windows 10
Firefox 50.0.2

**Comment by Logic-gate** [comment]
Hey,

I haven't been able to replicate this. Tested on linux FF 50.0.2 and Win10 50.0.2
If you dont have any tabs open, Yes it will 'tab--4 spaces' in the document, but when there are tabs, it switches between them.

**Comment by RedGearPro** [comment]
are you on multiprocess Firefox?

**Comment by Wohlstand** [comment]
Ctrl+tab is application reserved key combo. Usually that must be, or everyone can make non-escapable ad which opens more ads when you try to switch away from it. 
In most of MDI applications Ctrl+Tab is switching between opened files / tabs
