### ISSUE TITLE
Add Redis SSL support

### ISSUE THREAD

**Issue by phenomax** [toptal/haste-server#164]
Even if redis doesnt support SSL natively, many are using stunnel or another tls proxy to do so.

**Comment by acxe12** [comment]
update following packages:
    "redis": "2.8.0",
    "redis-url": "1.2.1"

and change lib/document_stores/redis.js 
  var auth = {auth_pass: options.password, tls: {servername: options.host}};
  RedisDocumentStore.client = redis.createClient(port, host, auth);


at least it helped to work with azure redis
