### ISSUE TITLE
It's impossible to use hastebin behind a proxy in a "subfolder" (domain.tld/haste)

### ISSUE THREAD

**Issue by benapetr** [toptal/haste-server#214]
I want to use hastebin on ports 80 and 443 on a server which already has a webserver, I followed the guide for proxy here: https://github.com/seejohnrun/haste-server/wiki/Installation

But it's bugged and even the author of patch to hastebin for "custom URL prefix" admits that there is a bug. When you use vanilla hastebin, it will always redirect url to / so:

test-site.org/haste will redirect to test-site.org/ immediately, breaking everything

and with the patch, it seems to work, but when you create a paste, generated URL won't open.

It would be nice to implement this into vanilla hastebin so that it's possible to use custom URLs while behind a proxy

**Comment by vwbusguy** [comment]
Can you post a snippet of your config?  I'm not a haste-server dev., but I've setup hastebin behind a proxy a few different times with success.  I'm most familiar with nginx for this setup.

**Comment by benapetr** [comment]
I will post the config, but can you tell me if you used the patch for this to work, or not? Also keep in mind that proxy probably works if hastebin is on dedicated domain, but not if you need to redirect it to some different folder, like your.domain/haste

**Comment by dordsor21** [comment]
This is still an issue.

**Comment by Mm2PL** [comment]
still seems to be an issue.

**Comment by BLANK-TH** [comment]
Still an issue

**Comment by manoaratefy** [comment]
Still an issue. My NGINX reverse proxy block:

```
location /bin/ {
    rewrite ^/bin/(.*)$ /$1 break;

    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Host $http_host;
    proxy_pass http://127.0.0.1:7777;
}
```

**Comment by marlon-schroder** [comment]
regardless, back to /

it is so hard make node route path option?

**Comment by TUBEOF** [comment]
Same problem here

**Comment by elwolf6** [comment]
pls figgs literally been 4 years

**Comment by dordsor21** [comment]
Not stale
