### ISSUE TITLE
Warning on quit

### ISSUE THREAD

**Issue by MatthewScholefield** [toptal/haste-server#217]
Just an idea, would it make sense to add a browser confirmation before closing the tab? Sometimes I find myself writing out a little demo code to share with someone and then end up erasing it by reloading the page or closing the tab.

If there is a concern for the nuisance of a confirmation when you only pasted useless data into it, the confirmation could only occur when the total number of key presses exceeds a certain number.

**Comment by seejohnrun** [comment]
@MatthewScholefield I think this might be a bit obtrusive just because most sites can close without confirmation.  Also there should be an entry in your history tab to get it back pretty quickly.  What do you think?

**Comment by MatthewScholefield** [comment]
@seejohnrun I don't see it as obtrusive if it only happens, lets say, when you typed more than 300 characters. Most of the time I just paste one or two things in there which would count as around 4 keypresses.

Another option is to just have it restore your state when you re-open the closed tab. This is how GitHub does it. Since, right now if you close it and then immediately reopen it, everything gets erased.

**Comment by seejohnrun** [comment]
Hey I just was re-reading this trying to clean up the repo a bit, and was wondering if the ask here is about files that you haven't saved ?

**Comment by MatthewScholefield** [comment]
Correct. Also for clarification, even for unsaved files, GitHub Gist retains state when closing the tab and reopening the tab (with something like ctrl+w, ctrl+shift+t)

**Comment by MatthewScholefield** [comment]
.
