### ISSUE TITLE
any fifo implem ideas?

### ISSUE THREAD

**Issue by imacks** [toptal/haste-server#228]
right now there is rate limit, expiry and paste length limit. however, docker doesn't really have an easy way to set disk space limits, so my entire nfs disk is available for when running as container. now i would like a fifo hard limit on the storage used, and when a new note comes in, i will remove some of the older notes to keep disk utilization below the limit. 

i guess this is a basic caching implementation. any ideas?

**Comment by seejohnrun** [comment]
I think this could be added to the redis strategy pretty easily by conditionally using something like `RPOPLPUSH / DELETE` to expire the oldest key when a new one comes in when the desired size gets reached (maybe using `DBINFO` if it should be conditional on size and not count) (and disabling expiration). 

I'm interested to hear if others have similar concerns and this would be used more widely

**Comment by imacks** [comment]
that sounds excellent. i figure nobody has that much ram to throw around, and it would be reasonable to set a limit here. the current implementation with redis would need me to place a hard memory limit on the container that runs redis, which would just make it slow and eventually crash when space runs out.
