### ISSUE TITLE
How can I disable language detection for the url?

### ISSUE THREAD

**Issue by jtagcat** [toptal/haste-server#312]
I'd like to disable the server appending stuff like coffescript to the end of the url.
A setting so instead of `https://pb.c7.ee/e81e.coffeescript` you always get `https://pb.c7.ee/e81e`.

**Comment by BeecherNetworks** [comment]
Is this not possible? The extensions seem kinda random.

**Comment by jtagcat** [comment]
> Is this not possible? The extensions seem kinda random.

It is possible, implement an if statement on the language detection (syntax highlighting) url part. Not in the mood right now, but might make a pr for this in some time.
(an another option would be to cut from dot to the end of generated url)

**Comment by seejohnrun** [comment]
Yeah this should be possible to implement as a feature, and I'd welcome a PR for it. I think that the extension feature is nice, so it'll remain in place for hastebin.com

**Comment by jtagcat** [comment]
Why close this issue, as not resolved?

**Comment by twiclo** [comment]
You should be able to change the extension to txt to get rid of highlighting

**Comment by jtagcat** [comment]
Yes, but defaulting to no extension / txt for the whole server is the thing here.

**Comment by seejohnrun** [comment]
Thanks @jtagcat happy to re-open this and get this implemented

**Comment by ACH1980** [comment]
Maybe we could make an optional field with the opportunity to add a extension. Then it wouldn't be possible to create Files without extension, but if you want you could say the system which file type it is or if you just want to disable syntax-Highlighting you could name it txt or somethin similar.

**Comment by ACH1980** [comment]
I'll have a look at the code, maybe I'll made a PR for that.

**Comment by kamilmirza** [comment]
got it!
comment the Line# 248-250 from [application.js](https://github.com/seejohnrun/haste-server/blob/master/static/application.js#L248-L250)

**Comment by jtagcat** [comment]
stale my ass

**Comment by twiclo** [comment]
Fork the repo, go to [this line](https://github.com/toptal/haste-server/blob/72863858338a57d54eb9dee55530e90ebbc22453/static/application.js#L28), and change the code block from
``` 
try {
    var high;
    if (lang === 'txt') {
        high = { value: _this.htmlEscape(res.data) };
    }
    else if (lang) {
        high = hljs.highlight(lang, res.data);
    }
    else {
        high = hljs.highlightAuto(res.data);
    }
}
 ```
to
```
try {
    var high = { value: _this.htmlEscape(res.data) };
}
```
Also you should really consider no longer supporting this repo. A lot of people have forked this project and are keeping it up to date. I've been running [this one](https://github.com/zneix/haste-server)

**Comment by twiclo** [comment]
Wait there's an even easier solution above

> got it! comment the Line# 248-250 from [application.js](https://github.com/seejohnrun/haste-server/blob/master/static/application.js#L248-L250)
