### ISSUE TITLE
CORS Support

### ISSUE THREAD

**Issue by IJustDev** [toptal/haste-server#352]
Hey there!

First of all thank you for this beautiful project. It's the easiest way I can imagine to share code and it helped me a lot.

I would like to use Hastebin in my project. Unfortunately the CORS request is failing. I would love to implement the CORS functionality to this server.

I've went through already closed issues and found #47 which seems similar.

**Comment by seejohnrun** [comment]
Hello are you looking to write data into a paste, or read data from an existing paste?

**Comment by IJustDev** [comment]
I am trying to create a new paste and read an existing one from an javascript client.

**Comment by codekrafter** [comment]
I am running into the same problem with CORS, any progress on supporting CORS? #353 looks like it could fix it.

**Comment by SilverCory** [comment]
Just a point to note, this could be used maliciously to gain more anonymity, not to mention potential abuse to overload the server as use for hosting such scripts.

**Comment by codekrafter** [comment]
There is already an API, this just lets web clients use it. I don't see how that allows any more malicious use as any malicious program could simply use a CORS proxy or call the API some other way
