### ISSUE TITLE
503 Service unavaible

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [toptal/haste-server#365]
I'm getting 503, when posting to https://hastebin.com/document
Some days ago it was working :C

**Comment by carldressler** [comment]
HTTP Error Code 503 aka "Service unavailable" indicates a server problem you cannot do anything about. Error codes starting with 500 are server-side while error codes starting with 400 are usually client-side.

**Comment by Kryniowesegryderiusz** [comment]
Ye, but isn't it official page of hastebin? I dont have idea where else I could report that this site is not working properly ;/

**Comment by slashinfty** [comment]
Judging by #251, this is the right place to put it. I'm also experiencing 503 errors.

**Comment by MACscr** [comment]
Its been down for me for awhile now. Stinks as I liked it. oh well.

**Comment by CraziiAce** [comment]
Does anyone else know a pastebin that can be POSTed to that's _not_ pastebin.com

**Comment by Favna** [comment]
> Does anyone else know a pastebin that can be POSTed to that's _not_ pastebin.com?

@CraziiAce https://hastebin.skyra.pw. I ["forked"](https://github.com/skyra-project/docker-images/tree/main/haste-server) this repo and made it available for the Skyra discord bot. We keep hastes in a redis instance and they're automatically pruned after 6 hours.
