### ISSUE TITLE
"Error adding document" when trying to add a document as normal

### ISSUE THREAD

**Issue by CraziiAce** [toptal/haste-server#370]
The error handler for a chatbot that I made posts the full traceback to hastebin.com using python requests:
```py
import requests

r = requests.post("https://hastebin.com/documents", data="foo bar")
```
This has been working well for me until lately, when I kept getting `{"message": "Error adding document"}` as the response. I've noticed that hastebin.com has been having high ping times lately, so maybe this could be an issue with lag on the server, but I don't know anything about JS so I have no idea if that is the case or if this could be caused by something else.

Anyways, any help with this would be appreciated.

Thanks!

**Comment by btn0s** [comment]
Also having this issue... can't use Hastebin online.

**Comment by dominiw** [comment]
The same issue!

**Comment by filipechagas** [comment]
Can't reproduce this error

Just tried:

```python
import requests

url = 'https://hastebin.com/documents'
response = requests.post(url, data = 'foo bar')
print(response.text)
```

And got:
```shell
$ python test.py
{"key":"bawoqaceri"}
```

**Comment by Nuckerr** [comment]
I've been getting this error while using my own self hosted haste-server and when I try to create a document from the website. I get this error in my dev tools
![image](https://user-images.githubusercontent.com/62883418/158081457-1a60b265-c474-4ace-9740-56b8f870efa5.png)
