### ISSUE TITLE
error "http://hastebin.com/undefined"

### ISSUE THREAD

**Issue by yuriw** [toptal/haste-server#372]
On Ubuntu 20.04 using hastebin from clipboard by Dave_Elec

In the logs:

`Mar 31 14:36:25 yuriw-RH2 gnome-shell[801110]: (../libsoup/soup-message.c:1098):soup_message_set_request: runtime check failed: (strchr (content_type, '/') != NULL) 
Mar 31 14:36:26 yuriw-RH2 gnome-shell[801110]: JS ERROR: Error: Source.notify() has been moved to Source.showNotification()this code will break in the future 
                                               notify@resource:///org/gnome/shell/ui/messageTray.js:865:23 
                                               hastebinFromClipboard/</<@/home/yuriw/.local/share/gnome-shell/extensions/hastebin-from-clipboard@dawitabate2@gmail.com/extension.js:60:32 
`

And hastebin shows `http://hastebin.com/undefined`

Any clues or fix how to work around this problem ?

**Comment by yuriw** [comment]
On Ubuntu 20.04 using hastebin from clipboard by Dave_Elec

In the logs:

`Mar 31 14:36:25 yuriw-RH2 gnome-shell[801110]: (../libsoup/soup-message.c:1098):soup_message_set_request: runtime check failed: (strchr (content_type, '/') != NULL) 
Mar 31 14:36:26 yuriw-RH2 gnome-shell[801110]: JS ERROR: Error: Source.notify() has been moved to Source.showNotification()this code will break in the future 
                                               notify@resource:///org/gnome/shell/ui/messageTray.js:865:23 
                                               hastebinFromClipboard/</<@/home/yuriw/.local/share/gnome-shell/extensions/hastebin-from-clipboard@dawitabate2@gmail.com/extension.js:60:32 
`
And hastebin shows `http://hastebin.com/undefined`

**Comment by SlyTheFloof** [comment]
KeyError: 'key'

**Comment by yuriw** [comment]
@SlyTheFloof can you elaborate pls?  can it be fixed?

**Comment by krvstianeq** [comment]
@yuriw Thats hastebin.com's server fault. Try to post something on haste.thxndy.tk
