### ISSUE TITLE
it looks like haste server is down again.

### ISSUE THREAD

**Issue by gamer-1478** [toptal/haste-server#379]
when trying hastebin/any_script.coffeescript, it is redirecting back to Hastebin.com and when trying to get raw data  it is saying document not found.

Also trying to save is not working as it says "error adding document"

**Comment by gamer-12748** [comment]
{"message":"Document not found."} when using hastebin.com/raw

**Comment by deniskaber** [comment]
Hello @gamer-1478. Thank you for the notification. Closing this as this seems to be not relevant anymore.
