### ISSUE TITLE
Add health endpoint

### ISSUE THREAD

**Issue by brunosaboia** [toptal/haste-server#383]
Hello,

The current health check done in Dockerfile is doing a `GET` request to `/`.

This is OK, but IMHO it would be a better idea to just have a `/health` endpoint, which would return an HTTP 204 for simplicity.

I could write a PR for this if it is deemed as a good idea.

Thanks.

**Comment by modem7** [comment]
+1 on this

**Comment by deniskaber** [comment]
Hello @brunosaboia! This sound like a good idea. Contributions are welcome.

**Comment by brunosaboia** [comment]
@deniskaber this repo seems dead. I created a PR related to tests a while ago, but nothing happened. Do you know about it?

**Comment by brunosaboia** [comment]
Nevermind, it got merged :)
