### ISSUE TITLE
Dockerhub Implementation

### ISSUE THREAD

**Issue by modem7** [toptal/haste-server#387]
For ease of use, would it be possible to have an official dockerhub implementation?

**Comment by Nicholaiii** [comment]
I don't think the project is maintained as much after the take-over, but I have published a docker image here on [GitHub Container Registry](https://github.com/Nicholaiii/haste-server/pkgs/container/haste-server).
I intend to integrate some current PRs and update deps, but the project is pretty hard to maintain, and could use a major refactor.

**Comment by konstrybakov** [comment]
Hi @modem7, thank you for taking the time to open this issue, we will look into this feature!

**Comment by delucca** [comment]
> Hi @modem7, thank you for taking the time to open this issue, we will look into this feature!

Looking forward for an official Docker image :)

**Comment by modem7** [comment]
Stalebot bump
