### ISSUE TITLE
Cant access key created my post request

### ISSUE THREAD

**Issue by Nuckerr** [toptal/haste-server#390]
Hello, so I am making a post request to `myhateserver.com/documents` and it replies with a key (all the right stuff), and I get this in my logs
![image](https://user-images.githubusercontent.com/62883418/135071729-e57c7c18-7a32-4027-8ce2-afba87a2d2f7.png)
However, when I then go to `myhasteserver.com/key` it redirects me to the home page and I get this warning: 
![image](https://user-images.githubusercontent.com/62883418/135071804-dd60f10b-0ba0-4b39-a338-3ca510c496e7.png)

My config:
```json
{

  "host": "localhost",
  "port": 7777,

  "keyLength": 10,

  "maxLength": 400000,

  "staticMaxAge": 86400,

  "recompressStaticAssets": true,

  "logging": [
    {
      "level": "verbose",
      "type": "Console",
      "colorize": true
    }
  ],

  "keyGenerator": {
    "type": "phonetic"
  },

  "rateLimits": {
    "categories": {
      "normal": {
        "totalRequests": 500,
        "every": 60000
      }
    }
  },

  "storage": {
    "path": "./data",
    "type": "file"
  },

  "documents": {
    "about": "./about.md"
  }

}
```

**Comment by Nuckerr** [comment]
Same issue is happening on `hastebin.com`

**Comment by konstrybakov** [comment]
I've checked this with your config and works fine. Can you confirm this is still an issue for you?

**Comment by Nuckerr** [comment]
I have since been able to use it. I think I misunderstood how to use the api
