### ISSUE TITLE
MongoDB not working.

### ISSUE THREAD

**Issue by typhoon11** [toptal/haste-server#394]
So I have my MongoDB atlas, when I am adding the URI of the database and using `npm start` it's throwing the error:

`db.collection('entries').update({
           ^
TypeError: db.collection is not a function`

My config.js is something like this:
![image](https://user-images.githubusercontent.com/66431066/137268338-7cd2bd6a-1cfc-45b5-a98f-9dd4eea6288f.png)

**Comment by ItsGamingTube** [comment]
Install mongodb 2.2.33 and it will work

**Comment by konstrybakov** [comment]
@typhoon11 Did the solution above solve your issue?

**Comment by typhoon11** [comment]
Yeah
