### ISSUE TITLE
3 moderate severity vulnerabilities

### ISSUE THREAD

**Issue by Owned67** [toptal/haste-server#395]
`F:\haste-server>npm install

added 204 packages, and audited 205 packages in 14s

10 vulnerabilities (8 moderate, 2 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
npm notice
npm notice New major version of npm available! 7.7.6 -> 8.1.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.1.0
npm notice Run npm install -g npm@8.1.0 to update!
npm notice

F:\haste-server> npm install -g npm@8.1.0

removed 220 packages, changed 3 packages, and audited 39 packages in 14s

1 moderate severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

F:\haste-server>npm audit fix

changed 44 packages, and audited 158 packages in 11s

7 packages are looking for funding
  run `npm fund` for details

# npm audit report

ansi-regex  >2.1.1 <5.0.1
Severity: moderate
 Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix`
node_modules/ansi-regex
  strip-ansi  4.0.0 - 5.2.0
  Depends on vulnerable versions of ansi-regex
  node_modules/strip-ansi
    string-width  2.1.0 - 4.1.0
    Depends on vulnerable versions of strip-ansi
    node_modules/string-width

3 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

F:\haste-server>npm audit fix

up to date, audited 158 packages in 2s

7 packages are looking for funding
  run `npm fund` for details

# npm audit report

ansi-regex  >2.1.1 <5.0.1
Severity: moderate
 Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix`
node_modules/ansi-regex
  strip-ansi  4.0.0 - 5.2.0
  Depends on vulnerable versions of ansi-regex
  node_modules/strip-ansi
    string-width  2.1.0 - 4.1.0
    Depends on vulnerable versions of strip-ansi
    node_modules/string-width

3 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix`

**Comment by deniskaber** [comment]
Thanks for the notification, @Owned67. Fixed
