### ISSUE TITLE
[QUESTION] what exactly is STORAGE_EXPIRE_SECONDS?

### ISSUE THREAD

**Issue by chibbi** [toptal/haste-server#406]
I am wondering what exactly gets expired when those seconds are reached.
It says that it is meant for keys inside of cache storages (redis, postgres, memcached).

Is it just how long a key is cached?
What is a key exactly?

**Comment by filipechagas** [comment]
Hello @chibbi 
Key Value storeage, like Redis, use a `key` to identify the resource. `STORAGE_EXPIRE_SECONDS` is the amount of seconds this k/v pair will exist in the storage.

Check [this out for more information](https://redis.io/commands/expire) on how that works in Redis.
