### ISSUE TITLE
Disable automatic closing of issues

### ISSUE THREAD

**Issue by C0rn3j** [toptal/haste-server#415]
If you are going to use stale bot to tag issues as stale ( https://github.com/toptal/haste-server/issues/191 ), at least do not automatically close them, I do not need notifications every 30 days and to spam all of my open bug reports just to keep them open.

**Comment by deniskaber** [comment]
Hey @C0rn3j !
One of our goals is to implement some support system to help us provide an even better open-source structure to the project. Therefore, we implemented the bot aiming to keep a cleaner repository by closing old opened issues. Anyway, we’re going to consider your concern and study how to make it more convenient for the reporters.
