### ISSUE TITLE
Tried to host haste-server on a Plesk webspace, error occured

### ISSUE THREAD

**Issue by byKeksYT** [toptal/haste-server#423]
Hey,

I tried to use haste-server on a webspace with Plesk, but as I configured it and started Node.js, the following error occured as shown in [this photo](https://verstandlxs.com/file/firefox_29_07_2022_20_17.png). It would be nice if anyone could give me tips on what am I possibly doing wrong. A web search on this error code brought no help, that's why I opened this issue here hoping for help.

**Comment by gOOvER** [comment]
this hav nothing to do with haste. Read the docu of plesk

**Comment by filipechagas** [comment]
Hy @byKeksYT 

I'm sorry you're having issues deploying haste-server. 
Unfortunately, we can't offer support deploying the app to different third parties.
