### ISSUE TITLE
503 error while post in /documents

### ISSUE THREAD

**Issue by Seyfle** [toptal/haste-server#424]
Hello everyone,

When I tried to post on the /documents routes hastebin give me a 503 error. (https://cdn.seyfle.fr/oa7s6hG9) 
Can someone help me ?

Thanks in advance

**Comment by filipechagas** [comment]
Hello @Seyfle 

Thanks for your report.

Can you please send us more details, please?
We'll need you to edit the issue and add: 
1. The exact command you used to make the post request. Was it `curl` or something else? Feel free to strip out any private content if that's your case.
2. The full error message formatted as code. Please do not post external links to screenshots or whatever. We'll not open them.

**Comment by Seyfle** [comment]
Nevermind, it's fixed... I don't konw how but it's fixed....

Thanks @filipechagas for your help and sorry for the inconvenience....
