### ISSUE TITLE
Release containers in a public repo

### ISSUE THREAD

**Issue by stavros-k** [toptal/haste-server#437]
It would be nice to have containers released from the original project, instead of relying on donwstreams to do that.
This will make sure the containers are inline with the latest versions.

Thanks

**Comment by konstrybakov** [comment]
Hey @stavros-k! Thank you for reaching out, the release of v2 is near https://github.com/toptal/haste-server/issues/429

With that ☝️ we will have an official Docker image :)

**Comment by Xstar97** [comment]
@konstrybakov do you plan on semVER release like X.X.X that would be greatly appreciated.

**Comment by konstrybakov** [comment]
Hey @Xstar97 from the release comment:

> Open-source version relaunch

> Following the relaunch, we'll closely monitor the initial weeks and concentrate on the open-source adjustments; to do this, we'll use the v2 branch.
