### ISSUE TITLE
Authentication failed (MongoDB)

### ISSUE THREAD

**Issue by stathri** [toptal/haste-server#440]
Hi, I'm having issues using MongoDB as storage. It worked up until I changed the username & database name. I did update both of those in the configuration file however it refuses to authenticate.

See the storage config below. I've removed the password and IP address for obvious reasons.
<img width="472" alt="image" src="https://user-images.githubusercontent.com/60489383/214620032-6213dcdf-b4fe-4ef4-a759-081368727740.png">

See the error below.
<img width="784" alt="image" src="https://user-images.githubusercontent.com/60489383/214619652-c5a73f36-6ab2-4d73-a326-71b0423fa5aa.png">

**Comment by filipechagas** [comment]
Hi @stathri 
I'm sorry you're having issues connecting with mongo.

I can't say for sure, but it seems your connection string is malformed. According [the documentation](https://www.mongodb.com/docs/manual/reference/connection-string/#standard-connection-string-format) the expected format is:
```
mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[defaultauthdb][?options]]
```

**Comment by stathri** [comment]
Hi, adding `?authSource=admin` seems to have fixed it.
