### ISSUE TITLE
1. Remove deprecation warning from existing trading-api hybrid websocket endpoint.

### ISSUE THREAD

**Issue by Algorithm1677** [toptal/haste-server#443]
1. Remove deprecation warning from existing trading-api hybrid websocket endpoint.
2. Sync with online docs.

_Originally posted by @dexterhuang-blockone in https://github.com/bullish-exchange/api-docs/pull/39_

**Comment by Reem-Dalal** [comment]
Hey! Can you please add some clarifications on why this is needed. Thank you 😄
